### ISSUE TITLE
在小米 8，MIUI10，8.7.26 ，Android 8.1.0 上，悬浮窗活不过五秒就消失了，即使我已经全部打开了所需权限

### ISSUE THREAD

**Issue by hidetag** [109021017/android-TopActivity#12]
在小米 8，MIUI10，8.7.26 ，Android 8.1.0 上，悬浮窗活不过五秒就消失了，即使我已经全部打开了所需权限

**Comment by 109021017** [comment]
把你的小米8, 插在电脑上, 运行 `adb shell getprop ro.build.version.sdk` 看下是什么结果

**Comment by hidetag** [comment]
API 版本是 27

**Comment by 109021017** [comment]
在 Android 8.1 的 Pixel 和 MIUI 9 Android 8.0 Mix2上均为复现你描述的问题. 因为手上没有相应版本的MIUI 设备, 无法进一步定位问题. 欢迎fork 一份代码, 在你的设备上debug 找到问题.

**Comment by hidetag** [comment]
Clone 后重新编译就生效了， 我之前的版本不知道是什么年代的了，所以没有做适配

**Comment by 109021017** [comment]
Feb 6, 2017 之前的版本

**Comment by PentonBin** [comment]
可以考虑将悬浮窗的windowType设置为TYPE_PHONE，设置为TYPE_TOAST可能会有这个问题 @hidetag
