### ISSUE TITLE
Android 7.1 no effect

### ISSUE THREAD

**Issue by XiangliJiaxing** [109021017/android-TopActivity#2]
android6.0之前,type_toast不需要权限；
但是部分非原生系统可能对源码进行了修改

android7.1开始，对type_toast这一类型做了限制，无任何效果
[https://android.googlesource.com/platform/frameworks/base/+/dc24f93 ](url)

综上所述，
建议type = 2003， 并且添加权限system_alert_window.

**Comment by 109021017** [comment]
是的, 在 [Google Play](https://play.google.com/store/apps/details?id=com.willme.topactivity) 发布的版本中已经修复了这个问题
Github 上的代码一直没有更新

**Comment by DysaniazzZ** [comment]
这个后来怎么解决的呢，改成`TYPE_SYSTEM_ALERT`，加上```<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>```都显示不出来了。

**Comment by 109021017** [comment]
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>`
而且要在系统中手动开启这个权限
`Settings.canDrawOverlays(this)` 检测是否获得权限
```
Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
intent.setData(Uri.parse("package:"+getPackageName()));
startActivity(intent);
```
跳转到系统设置设置这个权限
